function tapas_mpdcm_check_input_u(u)
%% Check that u is correct. 
%
% Input
%
% Output
%
% aponteeduardo@gmail.com
% copyright (C) 2015
%
%% Throws an error if something is wrong with u

assert(iscell(u), ...
    'mpdcm:int:input:u:not_cell', ...
    'u should be a cell array')

assert(ndims(u) == 2, ...
    'mpdcm:int:input:u:ndim', ...
    'u should be two dimensional, number of dimensions is %d', ndims(u))

su = size(u);

assert(su(2) == 1, ...
    'mpdcm:int:input:u:dsize', ...
    'Second dimension of u should have size 1, size is %d', su(2))

for i = 1:numel(u)
    assert(isnumeric(u{i}), ...
        'mpdcm:int:input:u:cell:not_numeric', ...
        'u{%d} should be numeric.', i);
    assert(ndims(u{i}) == 2, ...
        'mpdcm:int:input:u:cell:not_real', ...
        'u{%d} should be two dimensional.', i);
    assert(isreal(u{i}), ...
        'mpdcm:int:input:u:cell:not_real', ...
        'u{%d} should be real.', i);
    assert(~issparse(u{i}), ...
        'mpdcm:int:input:u:cell:sparse', ...
        'u{%d} should not be sparse', i);

    if i == 1
        os = size(u{i});
    end

    assert(all(os == size(u{i})), ...
        'mpdcm:int:input:u:cell:not_match', ...
        'All cells of u should have the same dimensions');
    os = size(u{i});
end
